name: "Python Poetry Action"
author: "@abatilo, @marius-cristian"
description: "An action to run https://github.com/python-poetry/poetry"
branding:
  icon: "truck"
  color: "gray-dark"
inputs:
  poetry-version:
    description: "The version of poetry to install"
    required: true
  poetry-plugins:
    description: "The whitespace/newline-separated list of poetry plugins to install."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - run: |
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
      shell: bash
    - run: |
        pipx install poetry==${{ inputs.poetry-version }}
      shell: bash
    - if: ${{ inputs.poetry-plugins != '' }}
      run: |
        ALL_PLUGINS=$(echo "${{ inputs.poetry-plugins }}")
        for PLUGIN in $ALL_PLUGINS; do
          poetry self add "$PLUGIN"
        done
      shell: bash
